name: Build Arch Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up pacman
        run: sudo apt-get install -y pacman

      - name: Install dependencies
        run: sudo pacman -Syu --noconfirm base-devel

      - name: Build package
        run: |
          cd local
          makepkg -s --noconfirm

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: arch-package
          path: local/*.pkg.tar.zst
